name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        # Instalar Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
        
        # Autenticar en Heroku
        echo $HEROKU_API_KEY | heroku auth:token
        
        # Agregar Heroku remote
        heroku git:remote -a $HEROKU_APP_NAME
        
        # Empujar cambios a Heroku
        git push heroku main