name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Programar para ejecutarse cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run the bot
      run: |
        nohup npm start &
        sleep 3600  # Mantener el bot activo durante 1 hora
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}